### ISSUE TITLE
Help to override ionic.scss's font-path to point to the correct path

### ISSUE THREAD

**Issue by gutomec** [DrMabuse23/generator-ionic-2#8]
Can you help me with this error please?

```
ERROR in ./~/css-loader?sourceMap!./~/resolve-url-loader!./~/autoprefixer-loader?browsers=last 2 version!./~/sass-loader?sourceMap!./app/main/main.scss
Module build failed: 
@import "../../node-modules/ionic-framework/ionic.ios";
^
      File to import not found or unreadable: ../../node-modules/ionic-framework/ionic.ios
Parent style sheet: stdin
      in /Users/gutomec/www/myApp_ionic_2/app/main/main.scss (line 51, column 1)
 @ ./app/main/main.scss 4:14-264 13:2-17:4 14:20-270
```

main.scss

``` scss
$font-path: '../../node-modules/ionic-framework/fonts';
$ionicons-font-path: $font-path;
// Ionic Sass
// ---------------------------------
@import "../../node-modules/ionic-framework/ionic.ios";
//@import "~ionic-framework/ionic.md";

// App Sass
// ---------------------------------
@import "../about/about", "../device/device";
```

BR,

**Comment by DrMabuse23** [comment]
Well maybe you have some more Information:

OS Type
Node version
node-sass version etc

**Comment by gutomec** [comment]
Hi DrMabuse23,

OSX   10.11.2
Node   v5.2.0
Npm   3.3.12

| ROOT | APP |
| --- | --- |
| => npm -g ls --depth=0 | => nam ls --depth=0 |
| /usr/local/lib | sexminer@0.0.1/Users/gutomec/www/myApp_ionic_2 |
| bower@1.7.1 | angular2@2.0.0-beta.0 |
| cordova@5.4.1 | angular2-jwt@0.1.3 extraneous |
| cordova-registry-mapper@1.1.14 | babel-core@6.3.26 |
| darwin@0.0.5 | babel-plugin-transform-es2015-modules-commonjs@6.3.16 |
| elementtree@0.1.6 | babel-preset-es2015@6.3.13 |
| generator-angular@0.15.1 | babel-runtime@6.3.19 |
| generator-angular-fullstack@3.1.1 | es6-shim@0.33.3 |
| generator-angular2@0.6.3 | gulp@3.9.0 |
| generator-ionic-2@0.1.6-beta | jasmine-core@2.4.1 |
| UNMETPEERDEPENDENCYgenerator-karma@>=0.9.0 | jspm@0.16.19 |
| generator-modern-web-dev@0.1.4 | karma-jasmine@0.3.6 |
| generator-webapp@1.1.0 | modern-web-dev-build@0.2.3 |
| grunt-cli@0.1.13 | nodemon@1.8.1 |
| gulp@3.9.0 | reflect-metadata@0.1.2 |
| imagemagick@0.1.3 | rxjs@5.0.0-beta.0 |
| ionic@1.7.12 | tsd@0.6.5 |
| ios-deploy@1.8.3 | typescript@1.7.3 |
| ios-sim@5.0.4 | └zone.js@0.5.10 |
| jshint@2.9.1-rc2 |  |
| jsonlint@1.6.2 |  |
| karma-cli@0.1.2 |  |
| mean-cli@0.10.17 |  |
| mup@0.11.3 |  |
| n@2.1.0 |  |
| node-gyp@3.2.1 |  |
| node-sass@3.4.2 |  |
| npm@3.3.12 |  |
| phonegap@5.3.9 |  |
| typescript@1.7.5 |  |
| typings@0.4.0 |  |
| webpack@1.12.9 |  |
| yo@1.5.1 |  |

BR,

**Comment by gutomec** [comment]
Hi DrMabuse23,

I installed node-sass module and made a new package of fresh installation.
Now the error is shown as follows:

```
WARNING in ./~/css-loader?sourceMap!./~/resolve-url-loader!./~/autoprefixer-loader?browsers=last 2 version!./~/sass-loader?sourceMap!./app/main/main.scss
  resolve-url-loader cannot operate: source-map error
  Cannot read property 'map' of undefined

ERROR in multi main
Module not found: Error: Cannot resolve module 'moment' in /Users/gutomec/www/teste
 @ multi main
webpack: bundle is now VALID.
```

I have high expectations for this package, and I can not wait that everything is 100% functional.

I had not installed the node-sass package earlier, and did not know it was a pre-requisite. I think maybe it would be a good idea to put in the package installation instructions.

BR,
