### ISSUE TITLE
'Zone is not defined' error after generator installed

### ISSUE THREAD

**Issue by nicholasglazer** [DrMabuse23/generator-ionic-2#9]
Ubuntu 15.10
npm -v 3.4.1
node -v 5.0.0

![bug_generator-ionic2](https://cloud.githubusercontent.com/assets/7410355/12074881/6b211d2a-b175-11e5-852f-60e3add56afe.png)

Have this error after installation. Any ideas?

**Comment by nicholasglazer** [comment]
I solved my problem with adding this code to main.js

``` javascript
import {enableProdMode} from 'angular2/core';
enableProdMode();
```

**Comment by DrMabuse23** [comment]
check this out http://stackoverflow.com/questions/34359303/zone-is-not-defined-for-ngzone-angular22-0-0-beta-0

angular2\ts\src\core\zone\ng_zone.ts@352 or angular2/src/core/zone/ng_zone.js

``` javascript
Zone.longStackTraceZone, {onError: function(e) { ngZone._notifyOnError(this, e); }});

//To

zone.longStackTraceZone, {onError: function(e) { ngZone._notifyOnError(this, e); }});
```
